version: "3.8"

services:
  code-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.code-server
    container_name: code-server
    environment:
      - PASSWORD=secret123
      - INTERVIEW_TAKEN_ID=${INTERVIEW_TAKEN_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    volumes:
      - ./workspace:/home/ubuntu/interviewer-env
    ports:
      - "8443:8080" # code-server port
      - "3000:3000" # frontend preview port
      - "5001:5001" # backend preview port
    depends_on:
      - db

  db:
    image: mongo:6.0
    container_name: interview-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpass
      MONGO_INITDB_DATABASE: testdb
    volumes:
      - db_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"

volumes:
  db_data: