version: '3.8'

services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    environment:
      - PASSWORD=secret123        # Change for production
    volumes:
      - ./workspace:/home/coder/project
    ports:
      - "8443:8080"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: interview-db
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=testdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  db_data:

