version: "3.8"

services:
  code-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.code-server
    container_name: code-server
    environment:
      - PASSWORD=secret123
      - INTERVIEW_TAKEN_ID=${INTERVIEW_TAKEN_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    volumes:
      - ./workspace:/home/ubuntu/interviewer-env
    ports:
      - "8443:8080" # code-server port
      - "3000:3000" # frontend preview port
      - "5000:5000" # backend preview port
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: interview-db
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  db_data:
