FROM codercom/code-server:latest

RUN apt-get update && apt-get install -y git

COPY startup.sh /usr/local/bin/startup.sh
RUN chmod +x /usr/local/bin/startup.sh

ENTRYPOINT ["/usr/local/bin/startup.sh"]